# Generated by Django 4.2.13 on 2024-06-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
